"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# print("settings.py __file__:", __file__)
# print("settings.py BASE_DIR:", BASE_DIR)
# settings.py __file__: /django-tutorial-4.2/mysite/mysite/settings.py
# settings.py BASE_DIR: /django-tutorial-4.2/mysite

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^gpqb4igo=!d%cxx8qu&9kag)!p95h3692$=avtyry2*2(yf+0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polls.apps.PollsConfig',
    'myapp.apps.MyappConfig',
    'myapp2.apps.Myapp2Config',
    'django_extensions',
    'myurl.apps.MyurlConfig',
    'book.apps.BookConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

################################################################

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "django.db": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "django.dispatch": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        }
    },
}

################################################################
"""
>>> from django.conf import settings
>>>
>>> dir(settings)
ABSOLUTE_URL_OVERRIDES
ADMINS
ALLOWED_HOSTS
APPEND_SLASH
AUTHENTICATION_BACKENDS
AUTH_PASSWORD_VALIDATORS
AUTH_USER_MODEL
BASE_DIR
CACHES
CACHE_MIDDLEWARE_ALIAS
CACHE_MIDDLEWARE_KEY_PREFIX
CACHE_MIDDLEWARE_SECONDS
CSRF_COOKIE_AGE
CSRF_COOKIE_DOMAIN
CSRF_COOKIE_HTTPONLY
CSRF_COOKIE_MASKED
CSRF_COOKIE_NAME
CSRF_COOKIE_PATH
CSRF_COOKIE_SAMESITE
CSRF_COOKIE_SECURE
CSRF_FAILURE_VIEW
CSRF_HEADER_NAME
CSRF_TRUSTED_ORIGINS
CSRF_USE_SESSIONS
DATABASES
DATABASE_ROUTERS
DATA_UPLOAD_MAX_MEMORY_SIZE
DATA_UPLOAD_MAX_NUMBER_FIELDS
DATA_UPLOAD_MAX_NUMBER_FILES
DATETIME_FORMAT
DATETIME_INPUT_FORMATS
DATE_FORMAT
DATE_INPUT_FORMATS
DEBUG
DEBUG_PROPAGATE_EXCEPTIONS
DECIMAL_SEPARATOR
DEFAULT_AUTO_FIELD
DEFAULT_CHARSET
DEFAULT_EXCEPTION_REPORTER
DEFAULT_EXCEPTION_REPORTER_FILTER
DEFAULT_FILE_STORAGE
DEFAULT_FROM_EMAIL
DEFAULT_INDEX_TABLESPACE
DEFAULT_TABLESPACE
DISALLOWED_USER_AGENTS
EMAIL_BACKEND
EMAIL_HOST
EMAIL_HOST_PASSWORD
EMAIL_HOST_USER
EMAIL_PORT
EMAIL_SSL_CERTFILE
EMAIL_SSL_KEYFILE
EMAIL_SUBJECT_PREFIX
EMAIL_TIMEOUT
EMAIL_USE_LOCALTIME
EMAIL_USE_SSL
EMAIL_USE_TLS
FILE_UPLOAD_DIRECTORY_PERMISSIONS
FILE_UPLOAD_HANDLERS
FILE_UPLOAD_MAX_MEMORY_SIZE
FILE_UPLOAD_PERMISSIONS
FILE_UPLOAD_TEMP_DIR
FIRST_DAY_OF_WEEK
FIXTURE_DIRS
FORCE_SCRIPT_NAME
FORMAT_MODULE_PATH
FORM_RENDERER
IGNORABLE_404_URLS
INSTALLED_APPS
INTERNAL_IPS
LANGUAGES
LANGUAGES_BIDI
LANGUAGE_CODE
LANGUAGE_COOKIE_AGE
LANGUAGE_COOKIE_DOMAIN
LANGUAGE_COOKIE_HTTPONLY
LANGUAGE_COOKIE_NAME
LANGUAGE_COOKIE_PATH
LANGUAGE_COOKIE_SAMESITE
LANGUAGE_COOKIE_SECURE
LOCALE_PATHS
LOGGING
LOGGING_CONFIG
LOGIN_REDIRECT_URL
LOGIN_URL
LOGOUT_REDIRECT_URL
MANAGERS
MEDIA_ROOT
MEDIA_URL
MESSAGE_STORAGE
MIDDLEWARE
MIGRATION_MODULES
MONTH_DAY_FORMAT
NUMBER_GROUPING
PASSWORD_HASHERS
PASSWORD_RESET_TIMEOUT
PREPEND_WWW
ROOT_URLCONF
SECRET_KEY
SECRET_KEY_FALLBACKS
SECURE_CONTENT_TYPE_NOSNIFF
SECURE_CROSS_ORIGIN_OPENER_POLICY
SECURE_HSTS_INCLUDE_SUBDOMAINS
SECURE_HSTS_PRELOAD
SECURE_HSTS_SECONDS
SECURE_PROXY_SSL_HEADER
SECURE_REDIRECT_EXEMPT
SECURE_REFERRER_POLICY
SECURE_SSL_HOST
SECURE_SSL_REDIRECT
SERVER_EMAIL
SESSION_CACHE_ALIAS
SESSION_COOKIE_AGE
SESSION_COOKIE_DOMAIN
SESSION_COOKIE_HTTPONLY
SESSION_COOKIE_NAME
SESSION_COOKIE_PATH
SESSION_COOKIE_SAMESITE
SESSION_COOKIE_SECURE
SESSION_ENGINE
SESSION_EXPIRE_AT_BROWSER_CLOSE
SESSION_FILE_PATH
SESSION_SAVE_EVERY_REQUEST
SESSION_SERIALIZER
SETTINGS_MODULE
SHORT_DATETIME_FORMAT
SHORT_DATE_FORMAT
SIGNING_BACKEND
SILENCED_SYSTEM_CHECKS
STATICFILES_DIRS
STATICFILES_FINDERS
STATICFILES_STORAGE
STATIC_ROOT
STATIC_URL
STORAGES
TEMPLATES
TEST_NON_SERIALIZED_APPS
TEST_RUNNER
THOUSAND_SEPARATOR
TIME_FORMAT
TIME_INPUT_FORMATS
TIME_ZONE
USE_DEPRECATED_PYTZ
USE_I18N
USE_L10N
USE_THOUSAND_SEPARATOR
USE_TZ
USE_X_FORWARDED_HOST
USE_X_FORWARDED_PORT
WSGI_APPLICATION
X_FRAME_OPTIONS
YEAR_MONTH_FORMAT
__class__
__delattr__
__dict__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__gt__
__hash__
__init__
__init_subclass__
__le__
__lt__
__module__
__ne__
__new__
__reduce__
__reduce_ex__
__repr__
__setattr__
__sizeof__
__str__
__subclasshook__
__weakref__
_explicit_settings
is_overridden
>>>
>>> settings.BASE_DIR
PosixPath('/django-tutorial-4.2/mysite')
>>>
>>> settings.SECRET_KEY
'django-insecure-^gpqb4igo=!d%cxx8qu&9kag)!p95h3692$=avtyry2*2(yf+0'
>>>
>>> settings.DEBUG
True
>>>
>>> settings.ALLOWED_HOSTS
[]
>>>
>>> settings.INSTALLED_APPS
[
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polls.apps.PollsConfig',
    'myapp.apps.MyappConfig',
    'myapp2.apps.Myapp2Config'
]
>>>
>>> settings.MIDDLEWARE
[
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]
>>>
>>> settings.ROOT_URLCONF
'mysite.urls'
>>>
>>> settings.TEMPLATES
[
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages'
            ]
        }
    }
]
>>>
>>> settings.WSGI_APPLICATION
'mysite.wsgi.application'
>>>
>>> settings.DATABASES
{
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': PosixPath('/django-tutorial-4.2/mysite/db.sqlite3'),
        'ATOMIC_REQUESTS': False,
        'AUTOCOMMIT': True,
        'CONN_MAX_AGE': 0,
        'CONN_HEALTH_CHECKS': False,
        'OPTIONS': {},
        'TIME_ZONE': None,
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
        'TEST': {
            'CHARSET': None,
            'COLLATION': None,
            'MIGRATE': True,
            'MIRROR': None,
            'NAME': None
        }
    }
}
>>>
>>> settings.AUTH_PASSWORD_VALIDATORS
[
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'}
]
>>>
>>> settings.LOGGING
{
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler'
        }
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING'
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False
        },
        'django.db': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False
        },
        'django.dispatch': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False
        }
    }
}
>>>

"""
